name: SkyBlockUI
main: therealkizu\skyblockui\Loader
version: 1.2.0-HoennPE
api: 3.0.0

softdepend:
  - RedSkyBlock
  - SkyBlock

# Extras
description: Manage your skyblock island in UI!
author: TheRealKizu, princepines (HoennPE)

# Permissions
permissions:
  sbui.command:
    description: Permission for the command /sbui
    default: true
