# Configuration file for SkyBlockUI
# Made by TheRealKizu (https://github.com/TheRealKizu)

# Options:
# giantquartz - If you want to use the SkyBlock plugin by QiantQuartz.
# redcraftgh - If you want to use RedSkyBlock by RedCraftGH.
# WARNING: RedSkyBlock support is currently in development!
skyblock-plugin: "giantquartz"