name: SkyBlockUI
main: therealkizu\skyblockui\Loader
version: 1.1.0
api: [3.0.0]
author: TheRealKizu

#Extra
website: https://therealkizu.tk
description: Legit SkyBlockUI! Exclusively for PocketMine-MP!
