name: SkyBlockUI
main: therealkizu\skyblockui\Loader
version: 1.1.0-beta2
api:
  - 3.0.0

depend:
  - SkyBlock

softdepend:
  - RedSkyBlock

# Extras
description: Legit SkyBlockUI! Exclusively for PocketMine-MP!
author: TheRealKizu
